program BSell;

{$R *.dres}

uses
  Forms,
  SysUtils,
  main in 'main.pas' {mainF},
  template0 in 'template0.pas' {template0F},
  template2MDI in 'template2MDI.pas' {template2MDIF},
  sort in '..\Generals\sort.pas' {sortF},
  Calculator in '..\Generals\Calculator.pas' {CalculatorF},
  filter_ADO in '..\Generals\filter_ADO.pas' {filterF},
  FilterClass_ADO in '..\Generals\FilterClass_ADO.pas',
  GeneralDM in '..\Generals\GeneralDM.pas' {GeneralDMF: TDataModule},
  MMESSAGE in '..\Generals\MMESSAGE.PAS' {mmessageF},
  search1 in '..\Generals\search1.pas' {searchF},
  searchCode_ADO4Scroll in '..\Generals\searchCode_ADO4Scroll.pas' {searchCode_ADO4ScrollF},
  shamsiDate in '..\Generals\shamsiDate.pas',
  SNDKEY32 in '..\Generals\SNDKEY32.PAS',
  CustGroups in 'CustGroups.pas' {CustGroupsF},
  Stores in 'Stores.pas' {StoresF},
  Sellers in 'Sellers.pas' {SellersF},
  CompanyBankAccounts in 'CompanyBankAccounts.pas' {CompanyBankAccountsF},
  StuffGroups2 in 'StuffGroups2.pas' {StuffGroups2F},
  Units in 'Units.pas' {UnitsF},
  CountingControlCode in 'CountingControlCode.pas' {CountingControlCodeF},
  template4 in 'template4.pas' {Template4F},
  UseUnitsNewEdit in 'UseUnitsNewEdit.pas' {UseUnitsNewEditF},
  Cashiers in 'Cashiers.pas' {CashiersF},
  Deficits in 'Deficits.pas' {DeficitsF},
  BookStuffCoding in 'BookStuffCoding.pas' {BookStuffCodingF},
  StuffCoding_EditNew in 'StuffCoding_EditNew.pas' {StuffCoding_EditNewF},
  OfficeCustomer in 'OfficeCustomer.pas' {OfficeCustomerF},
  ReciptsBuy in 'ReciptsBuy.pas' {ReciptsBuyF},
  UseUnits in 'UseUnits.pas' {UseUnitsF},
  ReciptTypes in 'ReciptTypes.pas' {ReciptTypesF},
  template5 in 'template5.pas' {Template5F},
  SelectStore in 'SelectStore.pas' {SelectStoreF},
  CheckCycle in 'CheckCycle.pas' {CheckCycleF},
  SelectCustomer in 'SelectCustomer.pas' {SelectCustomerF},
  GetCheck in 'GetCheck.pas' {GetCheckF},
  CofferFormTypes in 'CofferFormTypes.pas' {CofferFormTypesF},
  RecallRecipts in 'RecallRecipts.pas' {RecallReciptsF},
  StuffCodingSpecialSearch in 'StuffCodingSpecialSearch.pas' {StuffCodingSpecialSearchF},
  ChooseReciptOnFormsRange in 'ChooseReciptOnFormsRange.pas' {ChooseReciptOnFormsRangeF},
  rptStuffCodingMonths in 'rptStuffCodingMonths.pas' {rptStuffCodingMonthsF},
  rptStuffGroupsMonths in 'rptStuffGroupsMonths.pas' {rptStuffGroupsMonthsF},
  ReciptsBuyList in 'ReciptsBuyList.pas' {ReciptsBuyListF},
  PermitIssuance in 'PermitIssuance.pas' {PermitIssuanceF},
  rptBudgetRevenu in 'rptBudgetRevenu.pas' {rptBudgetRevenuF},
  CalculateOutPut in 'CalculateOutPut.pas' {CalculateOutPutF},
  RptEntityStuffGrpAllStore in 'RptEntityStuffGrpAllStore.pas' {RptEntityStuffGrpAllStoreF},
  RptReciptWithGrpCustMonths in 'RptReciptWithGrpCustMonths.pas' {RptReciptWithGrpCustMonthsF},
  rptFunctionComparison in 'rptFunctionComparison.pas' {rptFunctionComparisonF},
  RptReciptWithCustMonths in 'RptReciptWithCustMonths.pas' {RptReciptWithCustMonthsF},
  RptChecksIn in 'RptChecksIn.pas' {RptChecksInF},
  UpDateBank in 'UpDateBank.pas' {UpDateBankF},
  optionsAllSys in '..\Generals\optionsAllSys.pas' {optionsAllSysF},
  rptCofferTransAll in 'rptCofferTransAll.pas' {rptCofferTransAllF},
  rptCustTransDetails in 'rptCustTransDetails.pas' {rptCustTransDetailsF},
  rptCustomerCashTransacion in 'rptCustomerCashTransacion.pas' {rptCustomerCashtracsacionF},
  RptEntityStuffDetailsAllStore in 'RptEntityStuffDetailsAllStore.pas' {RptEntityStuffDetailsAllStoreF},
  RptBalanceCoffer in 'RptBalanceCoffer.pas' {rptBalanceCofferF},
  rptEntityOnDetailStuffsAllStore in 'rptEntityOnDetailStuffsAllStore.pas' {rptEntityOnDetailStuffsAllStoreF},
  rptCheckInForms in 'rptCheckInForms.pas' {rptCheckInFormsF},
  ManagGridColumns in '..\Generals\ManagGridColumns.pas' {ManagGridColumnsF},
  Counting in 'Counting.pas' {CountingF},
  Config in 'Config.pas' {ConfigF},
  Earth2 in 'Earth2.pas' {Earth2F},
  CountingItems in 'CountingItems.pas' {CountingItemsF},
  BudgetTopics2_EditNew in 'BudgetTopics2_EditNew.pas' {BudgetTopics2_EditNewF},
  BudgetTopicLevels in 'BudgetTopicLevels.pas' {BudgetTopicLevelsF},
  BudgetTopics2 in 'BudgetTopics2.pas' {BudgetTopics2F},
  BudgetTopicsRelation in 'BudgetTopicsRelation.pas' {BudgetTopicsRelationF},
  BudgetTopics1_NewEdit in 'BudgetTopics1_NewEdit.pas' {BudgetTopics1_NewEditF},
  BudgetTopics1 in 'BudgetTopics1.pas' {BudgetTopics1F},
  ChooseDiskMelat in 'ChooseDiskMelat.pas' {ChooseDiskMelatF},
  rptBudgetTransaction in 'rptBudgetTransaction.pas' {rptBudgetTransactionF},
  RptReciptWithCustItem in 'RptReciptWithCustItem.pas' {RptReciptWithCustItemF},
  RptReciptWithGrpCust in 'RptReciptWithGrpCust.pas' {RptReciptWithGrpCustF},
  rptFormsOnStuffMonths in 'rptFormsOnStuffMonths.pas' {rptFormsOnStuffMonthsF},
  rptFormsOnStuff in 'rptFormsOnStuff.pas' {rptFormsOnStuffF},
  rptStuffCoding in 'rptStuffCoding.pas' {rptStuffCodingF},
  rptRefineSell in 'rptRefineSell.pas' {rptRefineSellF},
  SMService in '..\Generals\SMService.pas' {SMServiceF},
  RptEntityStuffAllStore in 'RptEntityStuffAllStore.pas' {RptEntityStuffAllStoreF},
  Specialinventory in 'Specialinventory.pas' {SpecialinventoryF},
  PrintStuffLabel in 'PrintStuffLabel.pas' {PrintStuffLabelF},
  TrancService_Cust2 in 'TrancService_Cust2.pas' {TrancService_Cust2F},
  rptBalanceService in 'rptBalanceService.pas' {rptBalanceServiceF},
  TrancstuffDetails in 'TrancstuffDetails.pas' {TrancstuffDetailsF},
  MakeDocumentCoffer in 'MakeDocumentCoffer.pas' {MakeDocumentCofferF},
  MakeDocumentCheck in 'MakeDocumentCheck.pas' {MakeDocumentCheckF},
  rptBudget in 'rptBudget.pas' {rptBudgetF},
  Contract in 'Contract.pas' {ContractF},
  GetFirstEntity in 'GetFirstEntity.pas' {GetFirstEntityF},
  RptChecks4Print in 'RptChecks4Print.pas' {RptChecks4PrintF},
  StuffTransactionSum in 'StuffTransactionSum.pas' {StuffTransactionSumF},
  StuffGroupsTransaction in 'StuffGroupsTransaction.pas' {StuffGroupsTransactionF},
  rptUseUnit in 'rptUseUnit.pas' {rptUseUnitF},
  rptGroupUseUnit in 'rptGroupUseUnit.pas' {rptGroupUseUnitF},
  TarazGroupUseUnit in 'TarazGroupUseUnit.pas' {TarazGroupUseUnitF},
  rptHavaleh in 'rptHavaleh.pas' {rptHavalehF},
  rptCustTrancDetailsStuff in 'rptCustTrancDetailsStuff.pas' {rptCustTrancDetailsStuffF},
  rptCashier in 'rptCashier.pas' {rptCashierF},
  DataSet2Text in '..\Generals\DataSet2Text.pas' {DataSet2TextF},
  searchCheck in 'searchCheck.pas' {searchCheckF},
  ScheduleFinalProc in 'ScheduleFinalProc.pas' {ScheduleFinalProcF},
  ScheduleInfo in 'ScheduleInfo.pas' {ScheduleInfoF},
  ScheduleTypes in 'ScheduleTypes.pas' {ScheduleTypesF},
  ScheduleProcItems in 'ScheduleProcItems.pas' {ScheduleProcItemsF},
  ScheduleTimeTabel in 'ScheduleTimeTabel.pas' {ScheduleTimeTabelF},
  ScheduleTimeWorks in 'ScheduleTimeWorks.pas' {ScheduleTimeWorksF},
  RptScheduleTimeWorks in 'RptScheduleTimeWorks.pas' {RptScheduleTimeWorksF},
  RptCardMachines in 'RptCardMachines.pas' {RptCardMachinesF},
  RptScheduleTimeWorks_Loss in 'RptScheduleTimeWorks_Loss.pas' {RptScheduleTimeWorks_LossF},
  RptMashin_StuffLossItems in 'RptMashin_StuffLossItems.pas' {RptMashin_StuffLossItemsF},
  RptMashin_TimePerson in 'RptMashin_TimePerson.pas' {RptMashin_TimePersonF},
  RptMashin_WorksItems in 'RptMashin_WorksItems.pas' {RptMashin_WorksItemsF},
  RptCardexParentCo in 'RptCardexParentCo.pas' {RptCardexParentCoF},
  Samples in 'Samples.pas' {SamplesF},
  PurchaseEffect in 'PurchaseEffect.pas' {PurchaseEffectF},
  rptTrancDetails in 'rptTrancDetails.pas' {rptTrancDetailsF},
  rptTrans_Cust in 'rptTrans_Cust.pas' {rptTrans_CustF},
  rptBuySpecial in 'rptBuySpecial.pas' {rptBuySpecialF},
  RptEntityStuff in 'RptEntityStuff.pas' {RptEntityStuffF},
  RptControlEntity in 'RptControlEntity.pas' {RptControlEntityF},
  RptEntityStuffDetails in 'RptEntityStuffDetails.pas' {RptEntityStuffDetailsF},
  rptEntityOnDetailStuffs_wihtoutMoney in 'rptEntityOnDetailStuffs_wihtoutMoney.pas' {rptEntityOnDetailStuffs_wihtoutMoneyF},
  RptEntityStuffGrp in 'RptEntityStuffGrp.pas' {RptEntityStuffGrpF},
  rptAnalayzSells in 'rptAnalayzSells.pas' {rptAnalayzSellsF},
  LOGIN3 in '..\Generals\LOGIN3.pas' {login3F},
  rptCheckSadereh_State in 'rptCheckSadereh_State.pas' {rptcheckSadereh_StateF},
  RecallBranchChecks in 'RecallBranchChecks.pas' {RecallBranchChecksF},
  DailyWorkTow in 'DailyWorkTow.pas' {DailyWorkTowF},
  rptReportDailly in 'rptReportDailly.pas' {rptReportDaillyF},
  InitPop in '..\Generals\InitPop.pas',
  rptLoan in 'rptLoan.pas' {rptLoanF},
  rptCompare_Count_Entity in 'rptCompare_Count_Entity.pas' {rptCompare_Count_EntityF},
  PrintCountingLabel in 'PrintCountingLabel.pas' {PrintCountingLabelF},
  rptStuffGroups in 'rptStuffGroups.pas' {rptStuffGroupsF},
  rptCountingItemsCtrl in 'rptCountingItemsCtrl.pas' {rptCountingItemsCtrlF},
  vjForm1 in 'vjForm1.pas' {vjForm1F},
  ChooseDisk in 'ChooseDisk.pas' {ChooseDiskF},
  rptSupportCustMonths in 'rptSupportCustMonths.pas' {rptSupportCustMonthsF},
  rptSupportMonths in 'rptSupportMonths.pas' {rptSupportMonthsF},
  rptBuySpecialOnCostomers in 'rptBuySpecialOnCostomers.pas' {rptBuySpecialOnCostomersF},
  rptCustomerTrancItems in 'rptCustomerTrancItems.pas' {rptCustomerTrancItemsF},
  searchReports in '..\Generals\searchReports.pas',
  template2 in 'template2.pas' {template2F},
  DailyWork in 'DailyWork.pas' {DailyWorkF},
  Filters2 in '..\Generals\Filters2.pas' {Filters2F},
  Account in 'Account.pas' {Accountf},
  UseOthers in 'UseOthers.pas' {UseOthersF},
  ContractStuff in 'ContractStuff.pas' {ContractStuffF},
  rptInvoiceMatris in 'rptInvoiceMatris.pas' {rptInvoiceMatrisF},
  rptEntityOnDetailStuffs in 'rptEntityOnDetailStuffs.pas' {rptEntityOnDetailStuffsF},
  Note in 'Note.pas' {NoteF},
  RptReports in '..\Generals\RptReports.pas' {RptReportsF},
  SelectYear in '..\Generals\SelectYear.pas' {SelectYearF},
  ReciptsStore in 'ReciptsStore.pas' {ReciptsStoreF},
  RptOperational in 'RptOperational.pas' {RptOperationalF},
  StuffCodingMachinery2 in 'StuffCodingMachinery2.pas' {StuffCodingMachinery2F},
  ConversionCo in 'ConversionCo.pas' {ConversionCoF},
  rptOrderPointAnalytical in 'rptOrderPointAnalytical.pas' {rptOrderPointAnalyticalF},
  Recipts in 'Recipts.pas' {ReciptsF},
  RecallSpecialReciptsSum in 'RecallSpecialReciptsSum.pas' {RecallSpecialReciptsSumF},
  GetExcelMasterDetails in '..\Generals\GetExcelMasterDetails.pas' {GetExcelMasterDetailsF},
  AddToolbar in '..\Generals\AddToolbar.pas' {AddToolbarF},
  Special_Search in '..\Generals\Special_Search.pas' {special_SearchF},
  RptControlCardex2 in 'RptControlCardex2.pas' {RptControlCardex2F},
  StuffGroupsAccessory in 'StuffGroupsAccessory.pas' {StuffGroupsAccessoryF},
  NewYear in 'NewYear.pas' {NewYearF},
  rptCustomerTransaction in 'rptCustomerTransaction.pas' {rptCustomerTransactionF},
  LookUps in 'LookUps.pas' {LookUpsF},
  TshFunctionsCopy in 'TshFunctionsCopy.pas' {TshFunctionsCopyF},
  ExcelImportToTabel in 'ExcelImportToTabel.pas' {ExcelImportToTabelF},
  ExcelImport in 'ExcelImport.pas' {ExcelImportF},
  Maintenance in 'Maintenance.pas' {MaintenanceF},
  MakeDocument in 'MakeDocument.pas' {MakeDocumentF},
  otherCustomer in 'otherCustomer.pas' {otherCustomerF},
  LookUpNew in 'LookUpNew.pas' {LookUpNewF},
  ListUses in 'ListUses.pas' {ListUsesF},
  SearchComponents in '..\Generals\SearchComponents.pas' {SearchComponentsF},
  addRemoveRpt in '..\Generals\addRemoveRpt.pas' {addRemoveRptF},
  Earth in 'Earth.pas' {EarthF},
  RecallBranchChecksNew in 'RecallBranchChecksNew.pas' {RecallBranchChecksNewF},
  ExportXml in '..\Generals\ExportXml.pas',
  Loan in 'Loan.pas' {LoanF},
  StuffCodingToXml in 'StuffCodingToXml.pas' {StuffCodingToXmlF},
  SellPlan2 in 'SellPlan2.pas' {SellPlan2F},
  SelectedJunctionTable in '..\Generals\SelectedJunctionTable.pas' {SelectedJunctionTableF},
  Elaboration in 'Elaboration.pas' {ElaborationF},
  InvoiceEmission in 'InvoiceEmission.pas' {InvoiceEmissionF},
  InvoiceWithCash in 'InvoiceWithCash.pas' {InvoiceWithCashF},
  rptWorkCustomer in 'rptWorkCustomer.pas' {rptWorkCustomerF},
  RentRecipts in 'RentRecipts.pas' {RentReciptsF},
  RecallAcc in 'RecallAcc.pas' {RecallAccF},
  ShowpreReciptItemIDs in 'ShowpreReciptItemIDs.pas' {ShowpreReciptItemIDsF},
  Manifesto in 'Manifesto.pas' {ManifestoF},
  MachineStop in 'MachineStop.pas' {MachineStopF},
  Customers in 'Customers.pas' {CustomersF},
  FormDesign in 'FormDesign.pas' {FormDesignF},
  AddressInfo in 'AddressInfo.pas' {AddressInfoF},
  ChangeUnit in 'ChangeUnit.pas' {ChangeUnitF},
  MaliYear in '..\Generals\MaliYear.pas' {MaliYearF},
  AddressInMasir in 'AddressInMasir.pas' {AddressInMasirF},
  ShowPdf in '..\Generals\ShowPdf.pas' {ShowPdfF},
  ReciptRelease in 'ReciptRelease.pas' {ReciptReleaseF},
  ReciptsTrades in 'ReciptsTrades.pas' {ReciptsTradesF},
  DocRelated in 'DocRelated.pas' {DocRelatedF},
  MakeMaliYear in 'MakeMaliYear.pas' {MakeMaliYearF},
  RemainEarly in 'RemainEarly.pas' {RemainEarlyF},
  Agreements in 'Agreements.pas' {AgreementsF},
  Quota in 'Quota.pas' {QuotaF},
  ReciptsRegulation in 'ReciptsRegulation.pas' {ReciptsRegulationF},
  QuotaPost in 'QuotaPost.pas' {QuotaPostF},
  ReciptOnPersonel in 'ReciptOnPersonel.pas' {ReciptOnPersonelF},
  NoteBudject in 'NoteBudject.pas' {NoteBudjectF},
  RptReciptWithCust in 'RptReciptWithCust.pas' {RptReciptWithCustF},
  rptReciptListOnCustomers in 'rptReciptListOnCustomers.pas' {rptReciptListOnCustomersF},
  rptReciptListOnStuffCode in 'rptReciptListOnStuffCode.pas' {rptReciptListOnStuffCodeF},
  rptReciptSumOnStuffCodeCustomersItem in 'rptReciptSumOnStuffCodeCustomersItem.pas' {rptReciptSumOnStuffCodeCustomersItemF},
  rptReciptlistOnStuffCodeCustomersItem in 'rptReciptlistOnStuffCodeCustomersItem.pas' {rptReciptListOnStuffCodeCustomersItemF},
  rptReciptlistOnCustomersItem in 'rptReciptlistOnCustomersItem.pas' {rptReciptListOnCustomersItemF},
  rptReciptSumOnPersonID1 in 'rptReciptSumOnPersonID1.pas' {rptReciptSumOnPersonID1F},
  UpdateUnitSellPrice in 'UpdateUnitSellPrice.pas' {UpdateUnitSellPriceF},
  ChooseChecks in 'ChooseChecks.pas' {ChooseChecksF},
  RecallBranch in 'RecallBranch.pas' {RecallBranchF},
  ConsumptionStatistics in 'ConsumptionStatistics.pas' {ConsumptionStatisticsF},
  rptReciptSumOnCustomersItem in 'rptReciptSumOnCustomersItem.pas' {rptReciptSumOnCustomersItemF},
  StuffTransaction_ControlCode in 'StuffTransaction_ControlCode.pas' {StuffTransaction_ControlCodeF},
  dmgConst in 'dmgConst.pas' {dmgConstF: TDataModule},
  GetExcel in '..\Generals\GetExcel.pas' {GetExcelF},
  options in 'options.pas' {optionsF},
  StuffCodeSearch in 'StuffCodeSearch.pas' {StuffCodeSearchF},
  RecallBranchNew in 'RecallBranchNew.pas' {RecallBranchNewF},
  IniLang in '..\Generals\IniLang.pas',
  CofferGeneralReport in 'CofferGeneralReport.pas' {CofferGeneralReportF},
  StuffCodingSpecial in 'StuffCodingSpecial.pas' {StuffCodingSpecialF},
  ScanImage in '..\Generals\ScanImage.pas' {ScanImageF},
  Negotiations in 'Negotiations.pas' {NegotiationsF},
  Insurances in 'Insurances.pas' {InsurancesF},
  Costs in 'Costs.pas' {CostsF},
  ReciptsAnalysis in 'ReciptsAnalysis.pas' {ReciptsAnalysisF},
  MyDBGrids in '..\Generals\MyDBGrids.pas',
  RecallSpecialRecipts3 in 'RecallSpecialRecipts3.pas' {RecallSpecialRecipts3F},
  OfficesCoffer in 'OfficesCoffer.pas' {OfficesCofferF},
  RptCardex in 'RptCardex.pas' {RptCardexF},
  AccFunctions in '..\Generals\AccFunctions.pas',
  About in '..\Generals\About.pas' {aboutF},
  CPortFunctions in '..\Generals\CPortFunctions.pas',
  CheckDocument in '..\Generals\CheckDocument.pas',
  NumberToWords in '..\Generals\NumberToWords.pas',
  CdBurn in '..\Generals\CdBurn.pas' {CDBurnF},
  TopUpCalc in '..\Generals\TopUpCalc.pas' {TopUpCalcF},
  PaymentExpence in 'PaymentExpence.pas' {PaymentExpenceF},
  TshSchedules in 'TshSchedules.pas' {tshSchedulesF},
  sort2 in '..\Generals\sort2.pas' {sort2F},
  FaraConsts in 'FaraConsts.pas',
  RptCoffer in 'RptCoffer.pas' {rptCofferF},
  StuffCoding in 'StuffCoding.pas' {StuffCodingF},
  PaymentCash in 'PaymentCash.pas' {PaymentCashF},
  TshClockDmp in 'TshClockDmp.pas' {TshClockDmpF},
  MachinDelivery in 'MachinDelivery.pas' {MachinDeliveryF},
  SellPlan in 'SellPlan.pas' {SellPlanF},
  Cnt_RunScheduleItems in 'Cnt_RunScheduleItems.pas' {Cnt_RunScheduleItemsF},
  Cnt_Contracts2 in 'Cnt_Contracts2.pas' {Cnt_Contracts2F},
  Cnt_ContractOperations in 'Cnt_ContractOperations.pas' {Cnt_ContractOperationsF},
  Cnt_RunSchedules in 'Cnt_RunSchedules.pas' {Cnt_RunSchedulesF},
  HelpShow in '..\Generals\HelpShow.pas' {HelpShowF},
  GeneralReport in 'GeneralReport.pas' {GeneralReportF},
  KeyGenerator in '..\Generals\KeyGenerator.pas',
  SearchList in '..\Generals\SearchList.pas' {SearchListF},
  DocumentUpDate in 'DocumentUpDate.pas' {DocumentUpDateF},
  SomeChangeOrders in 'SomeChangeOrders.pas' {SomeChangeOrdersF},
  runScript in '..\Generals\runScript.pas' {runScriptF},
  DMSMS in '..\Generals\DMSMS.pas' {DMSMSF: TDataModule},
  BaseForm in '..\Generals\BaseForm.pas' {BaseFormF},
  infoSMS in '..\Generals\infoSMS.pas' {InfoSMSF},
  FrMakeDocs in 'frams\FrMakeDocs.pas' {frmMakeDocs: TFrame},
  DBGrid2Print in '..\Generals\DBGrid2Print.pas' {DBGrid2PrintF},
  Rpt001 in 'Rpt001.pas' {Rpt001F},
  FrPersonID3 in 'frams\FrPersonID3.pas' {frPersonID3F: TFrame},
  SearchRecipts in 'SearchRecipts.pas' {SearchReciptsF},
  rptDarayiSellsMonth in 'rptDarayiSellsMonth.pas' {rptDarayiSellsMonthF},
  RestoreDataBase in 'RestoreDataBase.pas' {RestoreDataBaseF},
  Related in 'Related.pas' {RelatedF},
  FrTax in 'frams\FrTax.pas' {frmTax: TFrame},
  FrProduction in 'frams\FrProduction.pas' {frmProduction: TFrame},
  ProductionForecasts2 in 'ProductionForecasts2.pas' {ProductionForecasts2F},
  FrTaxTxt in 'frams\FrTaxTxt.pas' {frmTaxTxt: TFrame},
  GeneralRegistration in 'GeneralRegistration.pas' {GeneralRegistrationF},
  ConversionCoCalc in 'ConversionCoCalc.pas' {ConversionCoCalcF},
  Severable in 'Severable.pas' {SeverableF},
  Zone in 'Zone.pas' {ZoneF},
  RptCardexSpecial in 'RptCardexSpecial.pas' {RptCardexSpecialF},
  Forwards2 in 'Forwards2.pas' {Forwards2F},
  RecallIndent in 'RecallIndent.pas' {RecallIndentF},
  RecallSpecialRecipts2 in 'RecallSpecialRecipts2.pas' {RecallSpecialRecipts2F},
  TshFunctions in 'TshFunctions.pas' {tshFunctionsF},
  SMSUnit in '..\Generals\SMSUnit.pas',
  DBGrid2GroupBy in '..\Generals\DBGrid2GroupBy.pas' {DBGrid2GroupByF},
  rptMailboxdatacontrol in 'rptMailboxdatacontrol.pas' {rptMailboxdatacontrolF},
  FlowForms in 'FlowForms.pas' {FlowFormsF},
  LanMessages in 'LanMessages.pas',
  rptCustomersBalance2 in 'rptCustomersBalance2.pas' {rptCustomersBalance2F},
  frEditImage in '..\Generals\frEditImage.pas' {frEditImageF: TFrame},
  StuffTranction_Detail in 'StuffTranction_Detail.pas' {StuffTranction_DetailF},
  ReciptPostOnCustomer in 'ReciptPostOnCustomer.pas' {ReciptPostOnCustomerF},
  MaintenanceGeneralReport in 'MaintenanceGeneralReport.pas' {MaintenanceGeneralReportF},
  FlowMaintenance in 'FlowMaintenance.pas' {FlowMaintenanceF},
  Resource in '..\Accounting\Units\Resource.pas',
  searchCode2_ADO in '..\Generals\searchCode2_ADO.pas' {searchCode2_ADOF},
  SelectedNew in 'SelectedNew.pas' {SelectedNewF},
  SelectedScaner in '..\Generals\SelectedScaner.pas' {SelectedScanerF},
  FaraDesktopAlert in '..\Generals\FaraDesktopAlert.pas',
  RecallCnt_Contracts2 in 'RecallCnt_Contracts2.pas' {RecallCnt_Contracts2F},
  Operators2 in '..\Generals\Operators2.pas' {Operators2F},
  ProductionForecasts in 'ProductionForecasts.pas' {ProductionForecastsF},
  StuffCodingItems in 'StuffCodingItems.pas' {StuffCodingItemsF},
  ListSQLServers in '..\Generals\ListSQLServers.pas',
  RecallTimeSheet in 'RecallTimeSheet.pas' {RecallTimeSheetF},
  Cnt_ContractsProperties in 'Cnt_ContractsProperties.pas' {Cnt_ContractsPropertiesF},
  TreeChart in '..\Generals\TreeChart.pas' {TreeChartF},
  GlobalPro in '..\Generals\GlobalPro.pas',
  ReciptsDeficitsPostAll in 'ReciptsDeficitsPostAll.pas' {ReciptsDeficitsPostAllF},
  ReciptsFunctions in 'Unit\ReciptsFunctions.pas',
  FormFunctions in 'Unit\FormFunctions.pas',
  selected in '..\Generals\selected.pas' {selectedF},
  CheckDocuments in 'CheckDocuments.pas' {CheckDocumentsF2},
  Mailboxdatacontrol in 'Mailboxdatacontrol.pas' {MailboxdatacontrolF},
  ReciptsPayments in 'ReciptsPayments.pas' {ReciptsPaymentsF},
  rptCardProject in 'rptCardProject.pas' {rptCardProjectF},
  rptCofferTrans2 in 'rptCofferTrans2.pas' {rptCofferTrans2F},
  search2 in '..\Generals\search2.pas' {search2F},
  StuffGroups_searchCode in 'StuffGroups_searchCode.pas' {StuffGroups_searchCodeF},
  StuffGroups in 'StuffGroups.pas' {StuffGroupsF},
  Forwards in 'Forwards.pas' {ForwardsF},
  TshGeneralReport in 'TshGeneralReport.pas' {tshGeneralReportF},
  TozinDeficits in 'TozinDeficits.pas' {TozinDeficitsF},
  ReciptsFund in 'ReciptsFund.pas' {ReciptsFundF},
  ReciptsPricing in 'ReciptsPricing.pas' {ReciptsPricingF},
  rptOrderControlPoint in 'rptOrderControlPoint.pas' {rptOrderControlPointF},
  StuffCodingMachinery in 'StuffCodingMachinery.pas' {StuffCodingMachineryF},
  MachineStop2 in 'MachineStop2.pas' {MachineStop2F},
  StuffCodingMachinery2Item in 'StuffCodingMachinery2Item.pas' {StuffCodingMachinery2ItemF},
  RequestManagement in 'RequestManagement.pas' {RequestManagementF},
  Position in '..\Generals\Position.pas' {PositionF},
  IntegrateDatabase in 'IntegrateDatabase.pas' {IntegrateDatabaseF},
  Allotment in 'Allotment.pas' {AllotmentF},
  editNew in '..\Generals\editNew.pas' {editNewF},
  WorkflowHistory in 'WorkflowHistory.pas' {WorkflowHistoryF},
  rptCountingItems in 'rptCountingItems.pas' {rptCountingItemsF},
  SendSMS in 'SendSMS.pas' {SendSMSF},
  WorkPlanning in 'WorkPlanning.pas' {WorkPlanningF},
  Marketting in 'Marketting.pas' {MarkettingF},
  CalcBasedFormula in '..\Generals\CalcBasedFormula.pas' {CalcBasedFormulaF},
  CustomerCheckList in 'CustomerCheckList.pas' {CustomerCheckListF},
  SWOT in 'SWOT.pas' {SWOTF},
  RptDesignForms in '..\Generals\RptDesignForms.pas' {rptDesignFormsF},
  rptCash in 'rptCash.pas' {rptCashF},
  Filters in '..\Generals\Filters.pas' {FiltersF},
  Filter_ADO_Const in 'Unit\Filter_ADO_Const.pas',
  RptScheduleTimeWorks_Stuff in 'RptScheduleTimeWorks_Stuff.pas' {RptScheduleTimeWorks_StuffF},
  SellPricing in 'SellPricing.pas' {SellPricingF},
  Offices in 'Offices.pas' {OfficesF},
  ConversionCoList in 'ConversionCoList.pas' {ConversionCoListF},
  CountingList in 'CountingList.pas' {CountingListF},
  ReciptsImport in 'ReciptsImport.pas' {template2MDIF2},
  CustomersMarketing in 'CustomersMarketing.pas' {CustomersMarketingF},
  GetAllReciptFromExl in 'GetAllReciptFromExl.pas' {GetAllReciptFromExlF},
  FrmServerName in '..\Generals\FrmServerName.pas' {frServerName: TFrame},
  RequestCash in 'RequestCash.pas' {RequestCashF},
  WorkflowDm in '..\Generals\WorkflowDm.pas' {WorkflowDmF: TDataModule},
  MainTaskList in '..\Generals\MainTaskList.pas' {MainTaskListF},
  WorkflowMain in '..\Generals\WorkflowMain.pas' {WorkflowMainF},
  Customers2 in 'Customers2.pas' {Customers2F},
  Artworks in 'Artworks.pas' {ArtworksF},
  FrDesign4LookUp in '..\Generals\FrDesign4LookUp.pas' {frmDesign4LookUp: TFrame},
  MakeDesignForms in 'MakeDesignForms.pas' {MakeDesignFormsF},
  MakeDocumentPost in 'MakeDocumentPost.pas' {MakeDocumentPostF},
  DesignForms in '..\Generals\DesignForms.pas' {DesignFormsF},
  Cnt_Contracts in 'Cnt_Contracts.pas' {Cnt_ContractsF},
  ActionPlans in 'ActionPlans.pas' {ActionPlansF},
  FrDBLookupComboBox in 'frams\FrDBLookupComboBox.pas' {frmDBLookupComboBox: TFrame},
  F5040 in 'F5040.pas' {F5040F},
  U5040 in 'Unit\U5040.pas',
  GetOtherMoney in 'GetOtherMoney.pas' {GetOtherMoneyF},
  Vcl.Themes,
  Vcl.Styles,
  Ratings in 'Ratings.pas' {RatingsF},
  FarsiReportBuilde in '..\Generals\FarsiReportBuilde.pas',
  Basis4CalculationFormulas in 'Basis4CalculationFormulas.pas' {Basis4CalculationFormulasF},
  SpecialAccDetailOnTopicBook in 'SpecialAccDetailOnTopicBook.pas' {SpecialAccDetailOnTopicBookF},
  ChangeCustID in 'ChangeCustID.pas' {ChangeCustIDF},
  ReviewOrders in 'ReviewOrders.pas' {ReviewOrdersF},
  FrReciptType in 'frams\FrReciptType.pas' {FrmReciptType: TFrame},
  FrVajheNaghd in 'frams\FrVajheNaghd.pas' {frmVajheNaghd: TFrame},
  FrRadioDisplayFormType in 'frams\FrRadioDisplayFormType.pas' {frmRadioDisplayFormType: TFrame},
  Telegram in '..\Generals\Telegram.pas',
  RecallSpecialReciptsEh in 'RecallSpecialReciptsEh.pas' {RecallSpecialReciptsEhF},
  uExtensionMethods in '..\FaraServiceManagement\FaraService\uExtensionMethods.pas',
  GeneralConst in '..\Generals\GeneralConst.pas',
  ProfitOrLosss in 'ProfitOrLosss.pas' {ProfitOrLosssF},
  Changer in '..\Generals\Changer.pas' {ChangerF},
  GetFaraFields in '..\Generals\GetFaraFields.pas' {GetFaraFieldsF},
  ExcelComparison in '..\Generals\ExcelComparison.pas' {ExcelComparisonF},
  InventoryByBarcode in 'InventoryByBarcode.pas' {InventoryByBarcodeF},
  ReviewRequests in 'ReviewRequests.pas' {ReviewRequestsF},
  ReciptsGrid in 'ReciptsGrid.pas' {ReciptsGridF},
  searchCode_ADO in '..\Generals\searchCode_ADO.pas' {searchCode_ADOF},
  GetTozin in 'GetTozin.pas' {GetTozinF},
  TozinList in 'TozinList.pas' {TozinListF},
  ExcelComparisonExcel2 in 'ExcelComparisonExcel2.pas' {ExcelComparisonExcel2F},
  GetCheckPostOverallType in 'GetCheckPostOverallType.pas' {GetCheckPostOverallTypeF},
  GroupReciptPost in 'GroupReciptPost.pas' {GroupReciptPostF},
  StoresAlternative in 'StoresAlternative.pas' {StoresAlternativeF},
  CustomersInterView in 'CustomersInterView.pas' {CustomersInterViewF},
  Ranking in 'Ranking.pas' {RankingF},
  CalcBasedFormula2 in 'CalcBasedFormula2.pas' {CalcBasedFormula2F},
  rptCustomersBalance in 'rptCustomersBalance.pas' {rptCustomersBalanceF},
  RecallSpecialRecipts in 'RecallSpecialRecipts.pas' {RecallSpecialReciptsF},
  frPelak in '..\Generals\frPelak.pas' {frPelakF: TFrame},
  mdiMain in 'mdiMain.pas' {mdiMainF},
  AssetsFunctions in 'Assets\Units\AssetsFunctions.pas',
  EditFirstDep in 'Assets\Forms\EditFirstDep.pas' {EditFirstDepF},
  AmvalNote in 'Assets\Forms\AmvalNote.pas' {AmvalNoteF},
  AidAssets in 'Assets\Forms\AidAssets.pas' {AidAssetsF},
  Amval in 'Assets\Forms\Amval.pas' {AmvalF},
  RptAmval in 'Assets\Forms\RptAmval.pas' {RptAmvalF},
  Expense1 in 'Assets\Forms\Expense1.pas' {Expense1F},
  SubCard in 'Assets\Forms\SubCard.pas' {SubCardF},
  Decrease in 'Assets\Forms\Decrease.pas' {DecreaseF},
  Movement in 'Assets\Forms\Movement.pas' {MovementF},
  BerakAmval in 'Assets\Forms\BerakAmval.pas' {BerakAmvalF},
  Revalidate in 'Assets\Forms\Revalidate.pas' {RevalidateF},
  AlterAmval in 'Assets\Forms\AlterAmval.pas' {AlterAmvalF},
  AlterAssets in 'Assets\Forms\AlterAssets.pas' {AlterAssetsF},
  InsouraceGroups in 'Assets\Forms\InsouraceGroups.pas' {InsouraceGroupsF},
  SpecialInsourance in 'Assets\Forms\SpecialInsourance.pas' {SpecialInsouranceF},
  AmvalCal in 'Assets\Forms\AmvalCal.pas' {AmvalCalF},
  AssetsMakeDocument in 'Assets\Forms\AssetsMakeDocument.pas' {AssetsMakeDocumentF},
  CleanDoc in 'Assets\Forms\CleanDoc.pas' {CleanDocF},
  AssetsConfig in 'Assets\Forms\AssetsConfig.pas' {AssetsConfigF},
  RptReports3200 in 'RptReports3200.pas' {RptReports3200F},
  frLookup_nonDB in '..\Generals\frLookup_nonDB.pas' {frLookup_nonDBF: TFrame},
  StuffTransaction in 'StuffTransaction.pas' {StuffTransactionF},
  rptDarayiSells in 'rptDarayiSells.pas' {rptDarayiSellsF},
  rptDarayiBuys in 'rptDarayiBuys.pas' {rptDarayiBuysF},
  ViewFile in '..\Generals\ViewFile.pas' {ViewFileF},
  RptReciptsRegulates in 'RptReciptsRegulates.pas' {RptReciptsRegulatesF},
  ReciptsRegulates in 'ReciptsRegulates.pas' {ReciptsRegulatesF},
  StuffToStore in 'StuffToStore.pas' {StuffToStoreF},
  ViewFileOnServer in '..\Generals\ViewFileOnServer.pas' {ViewFileOnServerF},
  SampleItems in 'SampleItems.pas' {SampleItemsF},
  SecurityForm in '..\Generals\SecurityForm.pas' {SecurityFormF},
  UFaraInterface in '..\Generals\UFaraInterface.pas',
  TozinPurchaseEffect in 'TozinPurchaseEffect.pas' {TozinPurchaseEffectF},
  CustomersTax in 'CustomersTax.pas' {CustomersTaxF},
  UTozin in 'Unit\UTozin.pas',
  Incorporate in 'Incorporate.pas' {IncorporateF},
  ReciptsDeficits in 'ReciptsDeficits.pas' {ReciptsDeficitsF},
  UModels in '..\Generals\UModels.pas',
  rptMatrixBalance in 'rptMatrixBalance.pas' {rptMatrixBalanceF},
  FrTreeChart in 'frams\FrTreeChart.pas' {frmTreeChart: TFrame},
  FrGetCheckPostOverallType in 'frams\FrGetCheckPostOverallType.pas' {frmGetCheckPostOverallType: TFrame},
  PanizSMS in '..\FaraServiceManagement\Generals\PanizSMS.pas',
  XmlMapper in '..\Generals\XmlMapper.pas' {XmlMapperF},
  NamaUnit in 'Unit\NamaUnit.pas',
  CustomersAlternative in 'CustomersAlternative.pas' {CustomersAlternativeF},
  RptControlCardex in 'RptControlCardex.pas' {RptControlCardexF},
  FrPlaqueReader in 'frams\FrPlaqueReader.pas' {frmPlaqueReader: TFrame},
  ReciptPurchaseEffect in 'ReciptPurchaseEffect.pas' {ReciptPurchaseEffectF},
  Ejare in 'Ejare.pas' {EjareF},
  rptDarayiEjare in 'rptDarayiEjare.pas' {rptDarayiEjareF},
  rptDarayiHagholAmalKari in 'rptDarayiHagholAmalKari.pas' {rptDarayiHagholAmalKariF},
  SpecialCodings in 'SpecialCodings.pas' {SpecialCodingsF},
  FrLoginKind in '..\Generals\FrLoginKind.pas' {frmLoginKind: TFrame},
  CheckCalc in 'CheckCalc.pas' {CheckCalcF},
  ExcelComparisonRecall in 'ExcelComparisonRecall.pas' {ExcelComparisonRecallF},
  AccessSend in '..\Generals\AccessSend.pas' {AccessSendF},
  DM in 'DM.pas' {DmF: TDataModule},
  ReciptItemsDetails in 'ReciptItemsDetails.pas' {ReciptItemsDetailsF},
  MahExUnit in 'Unit\MahExUnit.pas',
  HamTelUnit in 'Unit\HamTelUnit.pas',
  Pakings in 'Pakings.pas' {PakingsF},
  StuffDetails in 'StuffDetails.pas' {StuffDetailsF},
  ExcelConflict in 'ExcelConflict.pas' {ExcelConflictF},
  CountingDetails in 'CountingDetails.pas' {CountingDetailsF},
  rptCompare_Count_EntityD in 'rptCompare_Count_EntityD.pas' {rptCompare_Count_EntityDF},
  UAsanakSMS in '..\Generals\UAsanakSMS.pas',
  OperatorNotification in '..\Generals\OperatorNotification.pas' {OperatorNotificationF},
  OperatorNotification_U in '..\Generals\OperatorNotification_U.pas',
  RptTrialBalance_Details2 in 'RptTrialBalance_Details2.pas' {RptTrialBalance_DetailsF},
  UpdateExe in '..\Generals\UpdateExe.pas' {UpdateExeF},
  DMnipc in 'DMnipc.pas' {DMnipcF: TDataModule},
  Pkg.Json.DTO in 'Pkg.Json.DTO.pas',
  Unipc in 'Unipc.pas',
  num2char in '..\Generals\num2char.pas',
  BackupData in '..\Generals\BackupData.pas' {BackupDataF},
  MSPOSBAN_TLB in '..\Generals\MSPOSBAN_TLB.pas',
  RecallSpecialTozin in 'RecallSpecialTozin.pas' {RecallSpecialTozinF},
  GetAllFormFromExl in 'GetAllFormFromExl.pas' {GetAllFormFromExlF},
  Stereotypy in 'Stereotypy.pas' {StereotypyF},
  StereotypyShow in 'StereotypyShow.pas' {StereotypyShowF},
  AccTopicLevels in 'Finance\Forms\AccTopicLevels.pas' {AccTopicLevelsF},
  Categories in 'Finance\Forms\Categories.pas' {CategoriesF},
  DescTemplates in 'Finance\Forms\DescTemplates.pas' {DescTemplatesF},
  Detail_Relation in 'Finance\Forms\Detail_Relation.pas' {Detail_RelationF},
  DetailGroups in 'Finance\Forms\DetailGroups.pas' {DetailGroupsF},
  Portion_Relation2 in 'Finance\Forms\Portion_Relation2.pas' {Portion_Relation2F},
  DocCopy in 'Finance\Forms\DocCopy.pas' {DocCopyF},
  Details in 'Finance\Forms\Details.pas' {DetailsF},
  AccCode3 in 'Finance\Forms\AccCode3.pas' {AccCode3F},
  AccCode3F_EditNew in 'Finance\Forms\AccCode3F_EditNew.pas' {AccCode3F_EditNewF},
  accCode2 in 'Finance\Forms\accCode2.pas' {AccCode2F},
  Companies in 'Finance\Forms\Companies.pas' {CompaniesF},
  YearsTrialBalance in 'Finance\Forms\YearsTrialBalance.pas' {YearsTrialBalanceF},
  RptTrialBalance_Details in 'Finance\Forms\RptTrialBalance_Details.pas' {RptTrialBalance_DetailsF},
  AccBookAnalyze in 'Finance\Forms\AccBookAnalyze.pas' {AccBookAnalyzeF},
  AccDetailBookForSomeYear in 'Finance\Forms\AccDetailBookForSomeYear.pas' {AccDetailBookForSomeYearF},
  Rpt_Ctopics2OnDetailsBook in 'Finance\Forms\Rpt_Ctopics2OnDetailsBook.pas' {Rpt_Ctopics2OnDetailsBookF},
  Rpt_Ctopics2OnTopicBook in 'Finance\Forms\Rpt_Ctopics2OnTopicBook.pas' {Rpt_Ctopics2OnTopicBookF},
  Rpt_Ledger in 'Finance\Forms\Rpt_Ledger.pas' {Rpt_LedgerF},
  GeneralJournal in 'Finance\Forms\GeneralJournal.pas' {GeneralJournalF},
  FormTypes in 'Finance\Forms\FormTypes.pas' {FormTypesF},
  DocGroups in 'Finance\Forms\DocGroups.pas' {DocGrouspsF},
  FinancialTopics2 in 'Finance\Forms\FinancialTopics2.pas' {FinancialTopics2F},
  FinancialTopics2_EditNew in 'Finance\Forms\FinancialTopics2_EditNew.pas' {FinancialTopics2_EditNewF},
  FinancialTopics_Relation in 'Finance\Forms\FinancialTopics_Relation.pas' {FinancialTopics_RelationF},
  CategoresDetailNote in 'Finance\Forms\CategoresDetailNote.pas' {CategoresDetailNoteF},
  CToplic_Relation_2 in 'Finance\Forms\CToplic_Relation_2.pas' {CToplic_Relation_2F},
  FormInfo_Acc in 'Finance\Forms\FormInfo_Acc.pas' {FormInfo_AccF},
  BudgetRelation in 'Finance\Forms\BudgetRelation.pas' {BudgetRelationF},
  FinancialTopics_1 in 'Finance\Forms\FinancialTopics_1.pas' {FinancialTopics_1F},
  FinancialTopics_3 in 'Finance\Forms\FinancialTopics_3.pas' {FinancialTopics_3F},
  FinancialTopics_4 in 'Finance\Forms\FinancialTopics_4.pas' {FinancialTopics_4F},
  CToplic2_Relation in 'Finance\Forms\CToplic2_Relation.pas' {CToplic2_RelationF},
  rptJournal in 'Finance\Forms\rptJournal.pas' {rptJournalF},
  rptMonthDocuments in 'Finance\Forms\rptMonthDocuments.pas' {rptMonthDocumentsF},
  rptDailyDocuments in 'Finance\Forms\rptDailyDocuments.pas' {rptDailyDocumentsF},
  rptBalaceKollWithSomeColumn in 'Finance\Forms\rptBalaceKollWithSomeColumn.pas' {rptBalaceKollWithSomeColumnF},
  Eftetahieh in 'Finance\Forms\Eftetahieh.pas' {EftetahiehF},
  RptBalanceDetailWithSomeColumn in 'Finance\Forms\RptBalanceDetailWithSomeColumn.pas' {RptBalanceDetailWithSomeColumnF},
  SearchDocs in 'Finance\Forms\SearchDocs.pas' {SearchDocsF},
  AccComprasionMonthBalance in 'Finance\Forms\AccComprasionMonthBalance.pas' {AccComprasionMonthBalanceF},
  AccComprasionMonthCtopic2Balance in 'Finance\Forms\AccComprasionMonthCtopic2Balance.pas' {AccComprasionMonthCtopic2BalanceF},
  AccComprasionMonthDetailBalance in 'Finance\Forms\AccComprasionMonthDetailBalance.pas' {AccComprasionMonthDetailBalanceF},
  ChangeNum in 'Finance\Forms\ChangeNum.pas' {ChangeNumF},
  rptAnalyzeCormparisonBalance in 'Finance\Forms\rptAnalyzeCormparisonBalance.pas' {rptAnalyzeCormparisonBalanceF},
  ChooseCols in 'Finance\Forms\ChooseCols.pas' {ChooseColsF},
  AccBookForSomeYear in 'Finance\Forms\AccBookForSomeYear.pas' {AccBookForSomeYearF},
  RptTrialBalance_CTopics2_CTopics in 'Finance\Forms\RptTrialBalance_CTopics2_CTopics.pas' {RptTrialBalance_CTopics2_CTopicsF},
  CategoresCtopicNote in 'Finance\Forms\CategoresCtopicNote.pas' {CategoresCtopicNoteF},
  Rpt_CtopicsOnTopicBook in 'Finance\Forms\Rpt_CtopicsOnTopicBook.pas' {Rpt_CtopicsOnTopicBookF},
  FinancialTopics3_EditNew in 'Finance\Forms\FinancialTopics3_EditNew.pas' {FinancialTopics3_EditNewF},
  topicsNote in 'Finance\Forms\topicsNote.pas' {topicsNoteF},
  CtopicsNote in 'Finance\Forms\CtopicsNote.pas' {CtopicsNoteF},
  PortionTable in 'Finance\Forms\PortionTable.pas' {PortionTableF},
  CTopic2_AllRelation in 'Finance\Forms\CTopic2_AllRelation.pas' {CTopic2_AllRelationF},
  PortionRange_Relation in 'Finance\Forms\PortionRange_Relation.pas' {PortionRange_RelationF},
  PortionTopicCode in 'Finance\Forms\PortionTopicCode.pas' {PortionTopicCodeF},
  PortionRange in 'Finance\Forms\PortionRange.pas' {PortionRangeF},
  Portion_Relation in 'Finance\Forms\Portion_Relation.pas' {Portion_RelationF},
  Topic_Relation in 'Finance\Forms\Topic_Relation.pas' {Topic_RelationF},
  RptPortionShare in 'Finance\Forms\RptPortionShare.pas' {RptPortionShareF},
  DocTypes in 'Finance\Forms\DocTypes.pas' {DocTypesF},
  Rpt_CtopicsOnDetailsBook in 'Finance\Forms\Rpt_CtopicsOnDetailsBook.pas' {Rpt_CtopicsOnDetailsBookF},
  listPortionRange_2 in 'Finance\Forms\listPortionRange_2.pas' {listPortionRange_2F},
  DocTransaction in 'Finance\Forms\DocTransaction.pas' {DocTransactionF},
  DetailsNote in 'Finance\Forms\DetailsNote.pas' {DetailsNoteF},
  MakeDocPortionShare in 'Finance\Forms\MakeDocPortionShare.pas' {MakeDocPortionShareF},
  rptAnalyzeBalance in 'Finance\Forms\rptAnalyzeBalance.pas' {rptAnalyzeBalanceF},
  rptMatrixBalance2 in 'Finance\Forms\rptMatrixBalance2.pas' {rptMatrixBalance2F},
  BudgetInterface in 'Finance\Forms\BudgetInterface.pas' {BudgetInterfaceF},
  ChooseItems in 'Finance\Forms\ChooseItems.pas' {ChooseItemsF},
  ChooseItem2 in 'Finance\Forms\ChooseItem2.pas' {ChooseItem2F},
  BudjectInformation in 'Finance\Forms\BudjectInformation.pas' {BudjectInformationF},
  InportDocGroups in 'Finance\Forms\InportDocGroups.pas' {InportDocGroupsF},
  SpecialAccDetailOnTopicBook2 in 'Finance\Forms\SpecialAccDetailOnTopicBook2.pas' {SpecialAccDetailOnTopicBook2F},
  ChangeCodeDoc in 'Finance\Forms\ChangeCodeDoc.pas' {ChangeCodeDocF},
  Rpt_AccBook in 'Finance\Forms\Rpt_AccBook.pas' {Rpt_AccBookF},
  RptTrialBalance_Acc in 'Finance\Forms\RptTrialBalance_Acc.pas' {RptTrialBalance_AccF},
  CToplic3_Relation in 'Finance\Forms\CToplic3_Relation.pas' {CToplic3_RelationF},
  SendToDivan in 'Finance\Forms\SendToDivan.pas' {SendToDivanF},
  RelationGroupAcc in 'Finance\Forms\RelationGroupAcc.pas' {RelationGroupAccF},
  CheckPass in 'Finance\Forms\CheckPass.pas' {CheckPassF},
  ReViewCoding in 'Finance\Forms\ReViewCoding.pas' {ReViewCodingF},
  Contacts in 'Finance\Forms\Contacts.pas' {ContactsF},
  SpecialSearchDoc in 'Finance\Forms\SpecialSearchDoc.pas' {SpecialSearchDocF},
  AccCompare in 'Finance\Forms\AccCompare.pas' {AccCompareF},
  PortionTable2 in 'Finance\Forms\PortionTable2.pas' {PortionTable2F},
  MoveDoc in 'Finance\Forms\MoveDoc.pas' {MoveDocF},
  PortionInDoc in 'Finance\Forms\PortionInDoc.pas' {PortionInDocF},
  RptBalanceCtopicWithSomeColumn in 'Finance\Forms\RptBalanceCtopicWithSomeColumn.pas' {RptBalanceCtopicWithSomeColumnF},
  DocRelated2 in 'Finance\Forms\DocRelated2.pas' {DocRelated2F},
  rptAnalyzeBalanceMonth in 'Finance\Forms\rptAnalyzeBalanceMonth.pas' {rptAnalyzeBalanceMonthF},
  specialTrialBalance in 'Finance\Forms\specialTrialBalance.pas' {SpecialTrialBalanceF},
  ConfigTrial in 'Finance\Forms\ConfigTrial.pas' {ConfigTrialF},
  OfficesACC in 'Finance\Forms\OfficesACC.pas' {OfficesACCF},
  QuickSearch in 'Finance\Forms\QuickSearch.pas' {QuickSearchF: TFrame},
  FinanceReports in 'Finance\Forms\FinanceReports.pas' {FinanceReportsF},
  DefineReportItems in 'Finance\Forms\DefineReportItems.pas' {DefineReportItemsF},
  DefineReport in 'Finance\Forms\DefineReport.pas' {DefineReportF},
  RptFinanceReport in 'Finance\Forms\RptFinanceReport.pas' {RptFinanceReportF},
  SelectDefineReport in 'Finance\Forms\SelectDefineReport.pas' {SelectDefineReportF},
  VarianceBook in 'Finance\Forms\VarianceBook.pas' {VarianceBookF},
  listPortionRange in 'Finance\Forms\listPortionRange.pas' {listPortionRangeF},
  Ekhtetamie in 'Finance\Forms\Ekhtetamie.pas' {EkhtetanieF},
  DocumentSetting in 'Finance\Forms\DocumentSetting.pas' {DocumentSettingF},
  frYears in 'Finance\Forms\Frams\frYears.pas' {frYear: TFrame},
  RptTrialBalance_CTopics in 'Finance\Forms\RptTrialBalance_CTopics.pas' {RptTrialBalance_CTopicsF},
  AccUnits in 'Finance\Units\AccUnits.pas',
  XOptions in 'Finance\Units\XOptions.pas',
  Note_docGroup in 'Finance\Forms\Note_docGroup.pas' {Note_docGroupF},
  CToplic_Relation in 'Finance\Forms\CToplic_Relation.pas' {CToplic_RelationF},
  AccComprasionMonthCtopicBalance in 'Finance\Forms\AccComprasionMonthCtopicBalance.pas' {AccComprasionMonthCtopicBalanceF},
  Expense in 'Finance\Forms\Expense.pas' {ExpenseF},
  ExpenseList in 'Finance\Forms\ExpenseList.pas' {ExpenseListF},
  EmissionDoc in 'Finance\Forms\EmissionDoc.pas' {EmissionDocF},
  rptBudgect_WorkTopic in 'Finance\Forms\rptBudgect_WorkTopic.pas' {rptBudgect_WorkTopicF},
  rptBudgect_WorkTopicWithDetail in 'Finance\Forms\rptBudgect_WorkTopicWithDetail.pas' {rptBudgect_WorkTopicWithDetailF},
  frLookup in 'Finance\Forms\Frams\frLookup.pas' {frLookupF: TFrame},
  Manifest in 'Finance\Forms\Manifest.pas' {ManifestF},
  rptCurrency in 'Finance\Forms\rptCurrency.pas' {rptCurrencyF},
  rptAnalyzeAccountInfo in 'Finance\Forms\rptAnalyzeAccountInfo.pas' {rptAnalyzeAccountInfoF},
  RptTrialBalance_CTopics_Details in 'Finance\Forms\RptTrialBalance_CTopics_Details.pas' {RptTrialBalance_CTopics_DetailsF},
  Rpt_AccDetailOnTopicBook in 'Finance\Forms\Rpt_AccDetailOnTopicBook.pas' {Rpt_AccDetailOnTopicBookF},
  BudgetApproved in 'Finance\Forms\BudgetApproved.pas' {BudgetApprovedF},
  Commitments in 'Finance\Forms\Commitments.pas' {CommitmentsF},
  BudgetList in 'Finance\Forms\BudgetList.pas' {BudgetListF},
  BudgetItemsList in 'Finance\Forms\BudgetItemsList.pas' {BudgetItemsListF},
  BudgetReport in 'Finance\Forms\BudgetReport.pas' {BudgetReportF},
  BudgetTopicBook in 'Finance\Forms\BudgetTopicBook.pas' {BudgetTopicBookF},
  BudgetSettlement in 'Finance\Forms\BudgetSettlement.pas' {BudgetSettlementF},
  DocSanama in 'Finance\Forms\DocSanama.pas' {DocSanamaF},
  ContrastAccount in 'Finance\Forms\ContrastAccount.pas' {ContrastAccountF},
  AddAttachFile in 'Finance\Forms\AddAttachFile.pas' {AddAttachFileF},
  ImagePreview in 'Finance\Forms\ImagePreview.pas' {ImagePreviewF},
  UserDetailRelated in 'Finance\Forms\UserDetailRelated.pas' {UserDetailRelatedF},
  RptTrialBalance_AccCode_Arzi in 'Finance\Forms\RptTrialBalance_AccCode_Arzi.pas' {RptTrialBalance_AccCode_ArziF},
  Rpt_AccDetailOnTopicBook_Arzi in 'Finance\Forms\Rpt_AccDetailOnTopicBook_Arzi.pas' {Rpt_AccDetailOnTopicBook_ArziF},
  RptTrialDetailsBalance_Arzi in 'Finance\Forms\RptTrialDetailsBalance_Arzi.pas' {RptTrialDetailsBalance_ArziF},
  Rpt_AccBook_Arzi in 'Finance\Forms\Rpt_AccBook_Arzi.pas' {Rpt_AccBook_ArziF},
  CreateSanamaXML in 'Finance\Forms\CreateSanamaXML.pas' {CreateSanamaXMLF},
  VarianceBookBsell in 'Finance\Forms\VarianceBookBsell.pas' {VarianceBookBsellF},
  DocReference in 'Finance\Forms\DocReference.pas' {DocReferenceF},
  ReferenceToUser in 'Finance\Forms\ReferenceToUser.pas' {ReferenceToUserF},
  RptTrialBalance_CTopics2 in 'Finance\Forms\RptTrialBalance_CTopics2.pas' {RptTrialBalance_CTopics2F},
  RptTrialBalance_CTopics3 in 'Finance\Forms\RptTrialBalance_CTopics3.pas' {RptTrialBalance_CTopics3F},
  Rpt_Ctopics3OnTopicBook in 'Finance\Forms\Rpt_Ctopics3OnTopicBook.pas' {Rpt_Ctopics3OnTopicBookF},
  RptTrialBalance_CTopics3_CTopics in 'Finance\Forms\RptTrialBalance_CTopics3_CTopics.pas' {RptTrialBalance_CTopics3_CTopicsF},
  Rpt_Ctopics3OnDetailsBook in 'Finance\Forms\Rpt_Ctopics3OnDetailsBook.pas' {Rpt_Ctopics3OnDetailsBookF},
  VU_Financial_statement in 'Finance\Forms\VU_Financial_statement.pas' {VU_Financial_statementF},
  UserDetailRelated2 in 'Finance\Forms\UserDetailRelated2.pas' {UserDetailRelated2F},
  ExpenseCopy in 'Finance\Forms\ExpenseCopy.pas' {ExpenseCopyF},
  RptBalanceDetailWithSomeColumnKol in 'Finance\Forms\RptBalanceDetailWithSomeColumnKol.pas' {RptBalanceDetailWithSomeColumnKolF},
  MyReport in 'Finance\Forms\MyReport.pas',
  CreateDoc in 'Finance\Forms\CreateDoc.pas' {CreateDocF},
  Proforma in 'Proforma.pas' {ProformaF},
  Document in 'Finance\Forms\Document.pas' {DocumentF},
  ConfigAcc in 'Finance\Forms\ConfigAcc.pas' {ConfigAccF},
  SalaryFunctions in 'Salary\SalaryFunctions.pas',
  ConfigPay in 'Salary\ConfigPay.pas' {ConfigPayF},
  WordSend in 'Salary\WordSend.pas' {WordSendF},
  FormTypesPay in 'Salary\FormTypesPay.pas' {FormTypesPayF},
  FormInfo_1 in 'Salary\FormInfo_1.pas' {FormInfo_1F},
  ChooseItem in 'ChooseItem.pas' {ChooseItemF},
  FormInfo_4 in 'Salary\FormInfo_4.pas' {FormInfo_4F},
  FormInfo_3 in 'Salary\FormInfo_3.pas' {FormInfo_3F},
  FormInfo_2 in 'Salary\FormInfo_2.pas' {FormInfo_2F},
  JobsInfolist in 'Salary\JobsInfolist.pas' {JobsInfolistF},
  InsuranceCONSTinfo in 'Salary\InsuranceCONSTinfo.pas' {InsuranceCONSTinfoF},
  FunctionDayChek2 in 'Salary\FunctionDayChek2.pas' {FunctionDayChek2F},
  EmployeeLoanItem in 'Salary\EmployeeLoanItem.pas' {EmployeeLoanItemF},
  EmployeeDeeExtinfo in 'Salary\EmployeeDeeExtinfo.pas' {EmployeeDeeExtinfoF},
  PersonalArchive in 'Salary\PersonalArchive.pas' {PersonalArchiveF},
  PersonelFormInfo_1 in 'Salary\PersonelFormInfo_1.pas' {PersonelFormInfo_1F},
  rptFunctionItemYear in 'Salary\rptFunctionItemYear.pas' {rptFunctionItemYearF},
  InterdictEffectList in 'Salary\InterdictEffectList.pas' {InterdictEffectListF},
  FormInfo_6 in 'Salary\FormInfo_6.pas' {FormInfo_6F},
  InsouranceOther in 'Salary\InsouranceOther.pas' {InsouranceOtherF},
  PersonelDecExtinfo in 'Salary\PersonelDecExtinfo.pas' {PersonelDecExtinfoF},
  DecExtCalculate in 'Salary\DecExtCalculate.pas' {DecExtCalculateF},
  EmployeeDeeExtinfo_4 in 'Salary\EmployeeDeeExtinfo_4.pas' {EmployeeDeeExtinfo_4F},
  rptLoanSalary in 'Salary\rptLoanSalary.pas' {rptLoanSalaryF},
  RptFunctionWithMonth in 'Salary\RptFunctionWithMonth.pas' {RptFunctionWithMonthF},
  rptFunction4ProjectPerson in 'Salary\rptFunction4ProjectPerson.pas' {rptFunction4ProjectPersonF},
  MakeDskTax95 in 'Salary\MakeDskTax95.pas' {MakeDskTax95F},
  InterdictsEndDateWarn in 'Salary\InterdictsEndDateWarn.pas' {InterdictsEndDateWarnF},
  Interdicts4ItemsTide in 'Salary\Interdicts4ItemsTide.pas' {Interdicts4ItemsTideF},
  RetardListSalary in 'Salary\RetardListSalary.pas' {RetardListSalaryF},
  SalaryListProjectGroupYear in 'Salary\SalaryListProjectGroupYear.pas' {SalaryListProjectGroupYearF},
  rptLoanPersonel in 'Salary\rptLoanPersonel.pas' {rptLoanPersonelF},
  rptInsouranceOther2 in 'Salary\rptInsouranceOther2.pas' {rptInsouranceOther2F},
  SalaryList_Office in 'Salary\SalaryList_Office.pas' {SalaryList_OfficeF},
  SalaryList_Personel in 'Salary\SalaryList_Personel.pas' {SalaryList_PersonelF},
  SummerySalaryList_PersonelTotal2 in 'Salary\SummerySalaryList_PersonelTotal2.pas' {SummerySalaryList_PersonelTotal2F},
  KartSaat1_1 in 'Salary\KartSaat1_1.pas' {KartSaat1_1F},
  SalaryList4Project in 'Salary\SalaryList4Project.pas' {SalaryList4ProjectF},
  Interdicts4Form in 'Salary\Interdicts4Form.pas' {Interdicts4FormF},
  DetailInterdictList in 'Salary\DetailInterdictList.pas' {DetailInterdictListF},
  AllSalaryList in 'Salary\AllSalaryList.pas' {AllSalaryListF},
  rptPayableSalary in 'Salary\rptPayableSalary.pas' {rptPayableSalaryF},
  SalaryList4GetReprots in 'Salary\SalaryList4GetReprots.pas' {SalaryList4GetReprotsF},
  PersonelInfo in 'Salary\PersonelInfo.pas' {PersonelInfoF},
  PersonelInfoL2 in 'Salary\PersonelInfoL2.pas' {PersonelInfoL2F},
  RptCrossTab in 'Salary\RptCrossTab.pas' {RptCrossTabF},
  EditNewFormInfo_2 in 'Salary\EditNewFormInfo_2.pas' {EditNewFormInfo_2F},
  CalcAnnuity in 'Salary\CalcAnnuity.pas' {CalcAnnuityF},
  SalaryListTax in 'Salary\SalaryListTax.pas' {SalaryListTaxF},
  SalaryList_insurance2 in 'Salary\SalaryList_insurance2.pas' {SalaryList_insurance2F},
  SalaryList3col in 'Salary\SalaryList3col.pas' {SalaryList3colF},
  ListSalary in 'Salary\ListSalary.pas' {ListSalaryF},
  PersonelListPensioner in 'Salary\PersonelListPensioner.pas' {PersonelListPensionerF},
  SalaryList_insurancePart in 'Salary\SalaryList_insurancePart.pas' {SalaryList_insurancePartF},
  FunctionItems in 'Salary\FunctionItems.pas' {FunctionItemsF},
  ListBimehNew in 'Salary\ListBimehNew.pas' {ListBimehNewF},
  PersonelDecExt_111 in 'Salary\PersonelDecExt_111.pas' {PersonelDecExt_111F},
  PersonalTide in 'Salary\PersonalTide.pas' {PersonalTideF},
  MakeDocumentDec in 'Salary\MakeDocumentDec.pas' {MakeDocumentDecF},
  PersonelLeave in 'Salary\PersonelLeave.pas' {PersonelLeaveF},
  MissionItems in 'Salary\MissionItems.pas' {MissionItemsF},
  PersonelDecExtInfo_2 in 'Salary\PersonelDecExtInfo_2.pas' {PersonelDecExtInfo_2F},
  InterdictsWarn in 'Salary\InterdictsWarn.pas' {InterdictsWarnF},
  MissionInfo in 'Salary\MissionInfo.pas' {MissionInfoF},
  FormInfo_5Formula in 'Salary\FormInfo_5Formula.pas' {FormInfo_5FormulaF},
  SalaryOverTime in 'Salary\SalaryOverTime.pas' {SalaryOverTimeF},
  FunctionDayList in 'Salary\FunctionDayList.pas' {FunctionDayListF},
  FunctionDay in 'Salary\FunctionDay.pas' {FunctionDayF},
  SalaryList4Office in 'Salary\SalaryList4Office.pas' {SalaryList4OfficeF},
  ChangeWage in 'Salary\ChangeWage.pas' {ChangeWageF},
  ArchiveInfo2 in 'Salary\ArchiveInfo2.pas' {ArchiveInfo2F},
  calcArchiveInfo2 in 'Salary\calcArchiveInfo2.pas' {CalcArchiveInfo2F},
  KartSaat2_1 in 'Salary\KartSaat2_1.pas' {KartSaat2_1F},
  PersonelAccounts in 'Salary\PersonelAccounts.pas' {PersonelAccountsF},
  SalaryList4Office25Mission in 'Salary\SalaryList4Office25Mission.pas' {SalaryList4Office25MissionF},
  Interdicts in 'Salary\Interdicts.pas' {InterdictsF},
  Mission in 'Salary\Mission.pas' {MissionF},
  FunctionItems2 in 'Salary\FunctionItems2.pas' {FunctionItems2F},
  SalaryList4CTopicCode in 'Salary\SalaryList4CTopicCode.pas' {SalaryList4CTopicCodeF},
  CalcGETRemainedOffTime in 'Salary\CalcGETRemainedOffTime.pas' {CalcGETRemainedOffTimeF},
  TotalChange in '..\Generals\TotalChange.pas' {TotalChangeF},
  FunctionDayChek in 'Salary\FunctionDayChek.pas' {FunctionDayChekF},
  MakeDocumentPay in 'Salary\MakeDocumentPay.pas' {MakeDocumentPayF},
  MakeDocumentMission in 'Salary\MakeDocumentMission.pas' {MakeDocumentMissionF},
  SalaryList4Office25_2 in 'Salary\SalaryList4Office25_2.pas' {SalaryList4Office25_2F},
  EmployeeLoan in 'Salary\EmployeeLoan.pas' {EmployeeLoanF},
  RecOutMinistry in 'Salary\RecOutMinistry.pas' {RecOutMinistryF},
  KartSaat_donya in 'Salary\KartSaat_donya.pas' {KartSaat_donyaF},
  SalaryListGroup in 'Salary\SalaryListGroup.pas' {SalaryListGroupF},
  SalaryList4Office3Year in 'Salary\SalaryList4Office3Year.pas' {SalaryList4Office3YearF},
  SalaryList4Office25 in 'Salary\SalaryList4Office25.pas' {SalaryList4Office25F},
  Pony2 in 'Salary\Pony2.pas' {Pony2F},
  SalaryList4OfficeUnLimit in 'Salary\SalaryList4OfficeUnLimit.pas' {SalaryList4OfficeUnLimitF},
  MakeBankDsk in 'Salary\MakeBankDsk.pas' {MakeBankDSKF},
  GetReprots in 'Salary\GetReprots.pas' {GetReprotsF},
  SalaryList4SumOfficeUnLimit in 'Salary\SalaryList4SumOfficeUnLimit.pas' {SalaryList4SumOfficeUnLimitF},
  KartSaat_Win in 'Salary\KartSaat_Win.pas' {KartSaat_WinF},
  RetardSalaryList in 'Salary\RetardSalaryList.pas' {RetardSalaryListF},
  SummerySalaryList in 'Salary\SummerySalaryList.pas' {SummerySalaryListF},
  FunctionSpecialControl in 'Salary\FunctionSpecialControl.pas' {FunctionSpecialControlF},
  rptInsouranceOther in 'Salary\rptInsouranceOther.pas' {rptInsouranceOtherF},
  rptFunctionSpecialControl in 'Salary\rptFunctionSpecialControl.pas' {rptFunctionSpecialControlF},
  jobs in 'Salary\jobs.pas' {jobsF},
  convert in '..\Generals\convert.pas',
  FormDesignSalary in 'Salary\FormDesignSalary.pas' {FormDesignSalaryF},
  PersonelSponsorship in 'Salary\PersonelSponsorship.pas' {PersonelSponsorshipF},
  RecInMinistry in 'Salary\RecInMinistry.pas' {RecInMinistryF},
  CedarUnit in '..\Generals\CedarUnit.pas',
  SalaryList4Office2 in 'Salary\SalaryList4Office2.pas' {SalaryList4Office2F},
  SalaryEndService in 'Salary\SalaryEndService.pas' {SalaryEndServiceF},
  rptfunction in 'Salary\rptfunction.pas' {rptfunctionF},
  EmployeeInfolist in 'Salary\EmployeeInfolist.pas' {EmployeeInfolistF},
  SpAnalysisSalaryActualCosts in 'Salary\SpAnalysisSalaryActualCosts.pas' {SpAnalysisSalaryActualCostsF},
  ListPensioner in 'Salary\ListPensioner.pas' {ListPensionerF},
  frmInsouranceCheck in 'Salary\Frams\frmInsouranceCheck.pas' {frInsouranceCheck: TFrame},
  FrmTaxCheck in 'Salary\FrmTaxCheck.pas' {frTaxCheck: TFrame},
  Interdicts4Copy in 'Salary\Interdicts4Copy.pas' {Interdicts4CopyF},
  Interdicts4History in 'Salary\Interdicts4History.pas' {Interdicts4HistoryF},
  FunctionYears in 'Salary\FunctionYears.pas' {FunctionYearsF},
  SummerySalaryList_Personel in 'Salary\SummerySalaryList_Personel.pas' {SummerySalaryList_PersonelF},
  DecExtOnMounthSeparation in 'Salary\DecExtOnMounthSeparation.pas' {DecExtOnMounthSeparationF},
  DecExtOnMounth in 'Salary\DecExtOnMounth.pas' {DecExtOnMounthF},
  ADD2PersonelDecExt in 'Salary\ADD2PersonelDecExt.pas' {ADD2PersonelDecExtF},
  SalaryList4Office3 in 'Salary\SalaryList4Office3.pas' {SalaryList4Office3F},
  SalaryList4Office3YearDecWage in 'Salary\SalaryList4Office3YearDecWage.pas' {SalaryList4Office3YearDecWageF},
  VacationOver9 in 'Salary\VacationOver9.pas' {VacationOver9F},
  KartSaat_New in 'Salary\KartSaat_New.pas' {KartSaat_NewF},
  ExcelImportInterdicts in 'Salary\ExcelImportInterdicts.pas' {ExcelImportInterdictsF},
  ArchiveInfoFilter in 'Salary\ArchiveInfoFilter.pas' {ArchiveInfoFilterF},
  SpAnalysisSalary in 'Salary\SpAnalysisSalary.pas' {SpAnalysisSalaryF},
  ArchiveInfo in 'Salary\ArchiveInfo.pas' {ArchiveInfoF},
  ListSalaryKaroon in 'Salary\ListSalaryKaroon.pas' {ListSalaryKaroonF},
  GetReprotsKaroon in 'Salary\GetReprotsKaroon.pas' {GetReprotsKaroonF},
  FormInfo_5 in 'Salary\FormInfo_5.pas' {FormInfo_5F},
  frTaxKindCalc in 'Salary\frTaxKindCalc.pas' {frmTaxKindCalc: TFrame},
  PonyDebitCredit in 'Salary\PonyDebitCredit.pas' {PonyDebitCreditF},
  SummerySalaryList_PersonelTotal in 'Salary\SummerySalaryList_PersonelTotal.pas' {SummerySalaryList_PersonelTotalF},
  frmArchiveID in 'Salary\Frams\frmArchiveID.pas' {frArchiveID: TFrame},
  SalaryListProjectGroup in 'Salary\SalaryListProjectGroup.pas' {SalaryListProjectGroupF},
  Pony in 'Salary\Pony.pas' {PonyF},
  NotePay in 'Salary\NotePay.pas' {NotePayF},
  SalaryList_insurance in 'Salary\SalaryList_insurance.pas' {SalaryList_insuranceF},
  PonyList in 'Salary\PonyList.pas' {PonyListF},
  Interdicts4Items in 'Salary\Interdicts4Items.pas' {Interdicts4ItemsF},
  SalaryList4OfficeMonth in 'Salary\SalaryList4OfficeMonth.pas' {SalaryList4OfficeMonthF},
  rptFunctionYear in 'Salary\rptFunctionYear.pas' {rptFunctionYearF},
  SalaryList4Office25_UnLimit in 'Salary\SalaryList4Office25_UnLimit.pas' {SalaryList4Office25_UnLimitF},
  SendToOracel in 'Salary\SendToOracel.pas' {SendToOracelF},
  SalaryList_Project in 'Salary\SalaryList_Project.pas' {SalaryList_ProjectF},
  RecallBranchPay in 'Salary\RecallBranchPay.pas' {RecallBranchPayF},
  CdBurnTax in 'Salary\CdBurnTax.pas' {CdBurnTaxF},
  Zoom in 'Salary\Zoom.pas' {ZoomF},
  searchCode_TreeView in '..\Generals\searchCode_TreeView.pas' {searchCode_TreeViewF},
  searchCode_TreeViewB in 'searchCode_TreeViewB.pas' {searchCode_TreeViewBF},
  FormDesignAcc in 'Finance\Forms\FormDesignAcc.pas' {FormDesignAccF};

//---------------------------------------------------------

{$R *.res}

begin
  // if not ALLOWRUN then exit;
  if IsDelphiRunning then
    ReportMemoryLeaksOnShutdown := DebugHook <> 0;

  // Application.MainFormOnTaskbar:=False;
  SysLocale.FarEast := False;
  // Application.UpdateFormatSettings
  if DebugHook = 0 then
    aboutF.doQuick;

  Application.Initialize;
  Application.CreateForm(TDmF, DmF);
  Application.CreateForm(TGeneralDMF, GeneralDMF);
  Application.CreateForm(TmainF, mainF);
  Application.CreateForm(TWorkflowDmF, WorkflowDmF);
  Application.Run;

end.
