object CommonSelectedF: TCommonSelectedF
  Left = 0
  Top = 0
  BiDiMode = bdRightToLeft
  BorderStyle = bsToolWindow
  Caption = #1575#1606#1578#1582#1575#1576
  ClientHeight = 205
  ClientWidth = 237
  Color = 14145753
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  ParentBiDiMode = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
  object chklstSelect: TCheckListBox
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 231
    Height = 164
    Align = alClient
    Color = clInactiveCaption
    ItemHeight = 13
    TabOrder = 0
  end
  object Panel1: TPanel
    Left = 0
    Top = 170
    Width = 237
    Height = 35
    Align = alBottom
    TabOrder = 1
    object btnOk: TBitBtn
      AlignWithMargins = True
      Left = 158
      Top = 4
      Width = 75
      Height = 27
      Align = alRight
      Caption = #1578#1575#1740#1740#1583
      DoubleBuffered = True
      ModalResult = 1
      ParentDoubleBuffered = False
      TabOrder = 0
      ExplicitLeft = 128
      ExplicitTop = 6
      ExplicitHeight = 25
    end
    object btnCancel: TBitBtn
      AlignWithMargins = True
      Left = 4
      Top = 4
      Width = 75
      Height = 27
      Align = alLeft
      Caption = #1575#1606#1589#1585#1575#1601
      DoubleBuffered = True
      ModalResult = 2
      ParentDoubleBuffered = False
      TabOrder = 1
      ExplicitLeft = 77
      ExplicitTop = 6
    end
  end
end
