unit HamTelUnit;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65 
    Project link   : https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
    Generated On   : 2019-12-02 12:48:03

    Created By     : Petar Georgiev - (http://pgeorgiev.com) 
    Adapted Web By : Marlon Nardi - (http://jsontodelphi.com)
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json;

type

TProductsClass = class
private
  FCount: Extended;
  FId: Extended;
  FUnitprice: Extended;
public
  property count: Extended read FCount write FCount;
  property id: Extended read FId write FId;
  property unitprice: Extended read FUnitprice write FUnitprice;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TProductsClass;
end;

THamTelClass = class
private
  FOid: Extended;
  FProducts: TArray<TProductsClass>;
public
  property oid: Extended read FOid write FOid;
  property products: TArray<TProductsClass> read FProducts write FProducts;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): THamTelClass;
end;

implementation

{TProductsClass}


function TProductsClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TProductsClass.FromJsonString(AJsonString: string): TProductsClass;
begin
  result := TJson.JsonToObject<TProductsClass>(AJsonString)
end;

{THamTelClass}

destructor THamTelClass.Destroy;
var
  LproductsItem: TProductsClass;
begin

 for LproductsItem in FProducts do
   LproductsItem.Free;

  inherited;
end;

function THamTelClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function THamTelClass.FromJsonString(AJsonString: string): THamTelClass;
begin
  result := TJson.JsonToObject<THamTelClass>(AJsonString)
end;

end.
