unit MahExUnit;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65 
    Project link   : https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
    Generated On   : 2019-12-01 07:59:53

    Created By     : Petar Georgiev - (http://pgeorgiev.com) 
    Adapted Web By : Marlon Nardi - (http://jsontodelphi.com)
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json;

type

TParcelsClass = class
private
  FContent: String;
  FId: Extended;
  FWeight: Extended;
public
  property content: String read FContent write FContent;
  property id: Extended read FId write FId;
  property weight: Extended read FWeight write FWeight;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TParcelsClass;
end;

TTo_addressClass = class
private
  FCity_code: String;
  FFirst_name: String;
  FLast_name: String;
  FPhone: String;
  FStreet: String;
  FType: String;
public
  property city_code: String read FCity_code write FCity_code;
  property first_name: String read FFirst_name write FFirst_name;
  property last_name: String read FLast_name write FLast_name;
  property phone: String read FPhone write FPhone;
  property street: String read FStreet write FStreet;
  property &type: String read FType write FType;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TTo_addressClass;
end;

TMahExClass = class
private
  FParcels: TArray<TParcelsClass>;
  FReference: String;
  FTo_address: TTo_addressClass;
public
  property parcels: TArray<TParcelsClass> read FParcels write FParcels;
  property reference: String read FReference write FReference;
  property to_address: TTo_addressClass read FTo_address write FTo_address;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TMahExClass;
end;

implementation

{TParcelsClass}


function TParcelsClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TParcelsClass.FromJsonString(AJsonString: string): TParcelsClass;
begin
  result := TJson.JsonToObject<TParcelsClass>(AJsonString)
end;

{TTo_addressClass}


function TTo_addressClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TTo_addressClass.FromJsonString(AJsonString: string): TTo_addressClass;
begin
  result := TJson.JsonToObject<TTo_addressClass>(AJsonString)
end;

{TMahExClass}

constructor TMahExClass.Create;
begin
  inherited;
  FTo_address := TTo_addressClass.Create();
end;

destructor TMahExClass.Destroy;
var
  LparcelsItem: TParcelsClass;
begin

 for LparcelsItem in FParcels do
   LparcelsItem.Free;

  FTo_address.Free;
  inherited;
end;

function TMahExClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TMahExClass.FromJsonString(AJsonString: string): TMahExClass;
begin
  result := TJson.JsonToObject<TMahExClass>(AJsonString)
end;

end.
