unit NamaUnit;

// *************************************************
// Generated By: JsonToDelphiClass - 0.65
// Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
// Generated On: 2018-09-24 12:20:13
// *************************************************
// Created By  : Petar Georgiev - 2014
// WebSite     : http://pgeorgiev.com
// *************************************************

interface

uses Generics.Collections, Rest.Json, System.Json;

type

  TItemClass = class
  private
    FCityid: String;
    FCollectedcount: Real;
    FCollecteditem_price: Real;
    FPrice: String;
    FProduct_id: String;
    FReseller: String;
    FResellerid: String;
    FTitle: String;
    Fostan: string;
  public
    property cityid: String read FCityid write FCityid;
    property collectedcount: Real read FCollectedcount write FCollectedcount;
    property collecteditem_price: Real read FCollecteditem_price
      write FCollecteditem_price;
    property price: String read FPrice write FPrice;
    property product_id: String read FProduct_id write FProduct_id;
    property reseller: String read FReseller write FReseller;
    property resellerid: String read FResellerid write FResellerid;
    property title: String read FTitle write FTitle;
    property ostan: string read Fostan write Fostan;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TItemClass;
  end;

  TNamaClass = class
  private
    FItems: TArray<TItemClass>;
  public
    property Items: TArray<TItemClass> read FItems write FItems;
    destructor Destroy; override;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): Integer;
  end;

implementation

{ TItemClass }

function TItemClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TItemClass.FromJsonString(AJsonString: string): TItemClass;
begin
  result := TJson.JsonToObject<TItemClass>(AJsonString)
end;

{ TNamaClass }

destructor TNamaClass.Destroy;
var
  LItemsItem: TItemClass;
begin

  for LItemsItem in FItems do
    LItemsItem.free;

  inherited;
end;

function TNamaClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TNamaClass.FromJsonString(AJsonString: string): Integer;
var
  LJSONValue: TJSONArray;
  LItem: TJSONValue;
  item: TItemClass;
  Items: TArray<TItemClass>;
  i: Integer;
begin
  // result := TJson.JsonToObject<TNamaClass>(AJsonString)

  LJSONValue := TJSOnObject.ParseJSONValue(AJsonString) as TJSONArray;
  setlength(Items, LJSONValue.Count);
  i := 0;
  for LItem in LJSONValue do
  begin
    item := TJson.JsonToObject<TItemClass>(LItem.ToString);
    Items[i] := item;
    Inc(i);
  end;
  result := i;
  // TRootClass.FromJsonString('{"Items":[ ' + s + ']}');

end;

end.
