unit U5040;

// *************************************************
// Generated By: JsonToDelphiClass - 0.65
// Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
// Generated On: 2016-06-22 11:18:56
// *************************************************
// Created By  : Petar Georgiev - 2014
// WebSite     : http://pgeorgiev.com
// *************************************************

interface

uses Generics.Collections, Rest.Json, System.Json, System.SysUtils;

type

  // TStringArray = array of string;

  TMahsoulClass = class
  private
    FCodeGheymat: String;
    FCodeMahsoul: String;
    FCodeSarList: String;
    FCodeVahedShomaresh: Extended;
    FGheymatVahed: String;
    FMablaghNahayi: Extended;
    FOnvanMahsoul: String;
    FOnvaneVahedShomaresh: String;
    FSerialFaktor: String;
    FTakhfifMahsoul: String;
    FTedad: String;
  public
    property CodeSarList: String read FCodeSarList write FCodeSarList;
    property SerialFaktor: String read FSerialFaktor write FSerialFaktor;
    property CodeMahsoul: String read FCodeMahsoul write FCodeMahsoul;
    property OnvanMahsoul: String read FOnvanMahsoul write FOnvanMahsoul;
    property CodeGheymat: String read FCodeGheymat write FCodeGheymat;
    property GheymatVahed: String read FGheymatVahed write FGheymatVahed;
    property Tedad: String read FTedad write FTedad;
    property TakhfifMahsoul: String read FTakhfifMahsoul write FTakhfifMahsoul;
    property MablaghNahayi: Extended read FMablaghNahayi write FMablaghNahayi;
    property CodeVahedShomaresh: Extended read FCodeVahedShomaresh
      write FCodeVahedShomaresh;
    property OnvaneVahedShomaresh: String read FOnvaneVahedShomaresh
      write FOnvaneVahedShomaresh;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TMahsoulClass;
  end;

  TFaktorClass = class
  private
    FBimeVaAvarez: String;
    FCodeMeliMoshtari: String;
    FCodeMoshtari: String;
    FCodeNamayandegi: String;
    FCodePeygiri: String;
    FAddress: string;
    FCodePeyk: String;
    FCodeSarList: String;
    FHazineErsal: String;
    FMablaghKol: String;
    FMahsoul: TArray<TMahsoulClass>;
    FMaliat: String;
    FMobileMoshtari: String;
    FNameMoshtari: String;
    FNameNamayandegi: String;
    FNamePeyk: String;
    FNoePardakhtCode: String;
    FNoePardakht: String;
    FSerialFaktor: String;
    FTakhfif: String;
    FTarikhErsal: String;
    FTarikhFaktor: String;
    FTarikhSarList: String;
    FTarikhTaeinVaziat: String;
    FTedadFaktor: String;
    FTelMoshtari: String;
    FVaziarErsal: String;
    FVaziatPardakht: Boolean;
    FPersonalCode: String;
  published
    property BimeVaAvarez: String read FBimeVaAvarez write FBimeVaAvarez;
    property CodeMeliMoshtari: String read FCodeMeliMoshtari
      write FCodeMeliMoshtari;
    property CodeMoshtari: String read FCodeMoshtari write FCodeMoshtari;
    property CodeNamayandegi: String read FCodeNamayandegi
      write FCodeNamayandegi;
    property CodePeygiri: String read FCodePeygiri write FCodePeygiri;
    property Address: String read FAddress write FAddress;
    property CodePeyk: String read FCodePeyk write FCodePeyk;
    property CodeSarList: String read FCodeSarList write FCodeSarList;
    property HazineErsal: String read FHazineErsal write FHazineErsal;
    property Mahsoul: TArray<TMahsoulClass> read FMahsoul write FMahsoul;
    property Maliat: String read FMaliat write FMaliat;
    property MobileMoshtari: String read FMobileMoshtari write FMobileMoshtari;
    property NameMoshtari: String read FNameMoshtari write FNameMoshtari;
    property NameNamayandegi: String read FNameNamayandegi
      write FNameNamayandegi;
    property NamePeyk: String read FNamePeyk write FNamePeyk;
    property NoePardakhtCode: String read FNoePardakhtCode write FNoePardakhtCode;
    property NoePardakht: String read FNoePardakht write FNoePardakht;
    property SerialFaktor: String read FSerialFaktor write FSerialFaktor;
    property Takhfif: String read FTakhfif write FTakhfif;
    property TarikhErsal: String read FTarikhErsal write FTarikhErsal;
    property TarikhFaktor: String read FTarikhFaktor write FTarikhFaktor;
    property TarikhSarList: String read FTarikhSarList write FTarikhSarList;
    property TarikhTaeinVaziat: String read FTarikhTaeinVaziat
      write FTarikhTaeinVaziat;
    property TedadFaktor: String read FTedadFaktor write FTedadFaktor;
    property TelMoshtari: String read FTelMoshtari write FTelMoshtari;
    property VaziarErsal: String read FVaziarErsal write FVaziarErsal;
    property VaziatPardakht: Boolean read FVaziatPardakht write FVaziatPardakht;
    property MablaghKol: String read FMablaghKol write FMablaghKol;
    property PersonalCode: String read FPersonalCode write FPersonalCode;
    destructor Destroy; override;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TFaktorClass;
  end;

  TSarListClass = class
  private
    FFaktor: TArray<TFaktorClass>;
  public
    property Faktor: TArray<TFaktorClass> read FFaktor write FFaktor;
    destructor Destroy; override;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TSarListClass;
  end;

  T5040Class = class
  private
    FSarList: TArray<TSarListClass>;
  public
    property SarList: TArray<TSarListClass> read FSarList write FSarList;
    destructor Destroy; override;
	
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): T5040Class;
  end;

implementation

uses
  MMESSAGE;

{ TMahsoulClass }

function TMahsoulClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TMahsoulClass.FromJsonString(AJsonString: string): TMahsoulClass;
begin
  result := TJson.JsonToObject<TMahsoulClass>(AJsonString)
end;

{ TFaktorClass }

destructor TFaktorClass.Destroy;
var
  LMahsoulItem: TMahsoulClass;
begin

  for LMahsoulItem in FMahsoul do
    LMahsoulItem.free;

  inherited;
end;

function TFaktorClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TFaktorClass.FromJsonString(AJsonString: string): TFaktorClass;
begin
  result := TJson.JsonToObject<TFaktorClass>(AJsonString)
end;

{ TSarListClass }

destructor TSarListClass.Destroy;
var
  LFaktorItem: TFaktorClass;
begin

  for LFaktorItem in FFaktor do
    LFaktorItem.free;

  inherited;
end;

function TSarListClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TSarListClass.FromJsonString(AJsonString: string): TSarListClass;
begin
  result := TJson.JsonToObject<TSarListClass>(AJsonString)
end;

{ T5040Class }

destructor T5040Class.Destroy;
var
  LSarListItem: TSarListClass;
begin

  for LSarListItem in FSarList do
    LSarListItem.free;

  inherited;
end;

function T5040Class.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function T5040Class.FromJsonString(AJsonString: string): T5040Class;
begin
  result := TJson.JsonToObject<T5040Class>(AJsonString)
end;

end.
