object frmShowWarn: TfrmShowWarn
  Left = 0
  Top = 0
  Width = 468
  Height = 358
  BiDiMode = bdRightToLeft
  ParentBiDiMode = False
  TabOrder = 0
  object lstWarn: TListBox
    Left = 0
    Top = 0
    Width = 468
    Height = 358
    Style = lbOwnerDrawFixed
    Align = alClient
    BiDiMode = bdLeftToRight
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ItemHeight = 16
    ParentBiDiMode = False
    ParentFont = False
    TabOrder = 0
    OnDrawItem = lstWarnDrawItem
  end
end
